WebAdvert.Web/Controllers/AccountsController.cs
using Amazon.AspNetCore.Identity.Cognito;
using Amazon.Extensions.CognitoAuthentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAdvert.Web.Models.Accounts;

namespace WebAdvert.Web.Controllers
{
    public class AccountsController : Controller
    {
        private readonly SignInManager<CognitoUser> _signInManager;
        private readonly UserManager<CognitoUser> _userManager;
        private readonly CognitoUserPool _cognitoUserPool;

        public AccountsController(SignInManager<CognitoUser> signInManager, 
                        UserManager<CognitoUser> userManager, 
                        CognitoUserPool cognitoUserPool)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _cognitoUserPool = cognitoUserPool;
        }

        [HttpGet]
        public async Task<IActionResult> SignUp()
        {
            var model = new SignUp();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(SignUp model)
        {
            if (ModelState.IsValid)
            {
                var user = _cognitoUserPool.GetUser(model.Email);
                if (user.Status != null)
                {
                    ModelState.AddModelError("UserExists", "User with this email already exists");
                    return View(model);
                }

                user.Attributes.Add(CognitoAttribute.Name.AttributeName, model.Email);
                var createdUser = await _userManager.CreateAsync(user, model.Password).ConfigureAwait(false);
                if (createdUser.Succeeded)
                {
                    return RedirectToAction("ConfirmAccount");
                }
                else
                {
                    var findUser = await _userManager.FindByEmailAsync(model.Email).ConfigureAwait(false);
                    if (findUser != null && findUser.Status == "UNCONFIRMED")
                    {
                        findUser.ResendConfirmationCodeAsync().Wait();
                        return RedirectToAction("ConfirmAccount");
                    }
                }
                if(createdUser.Errors != null)
                {
                    foreach(var error in createdUser.Errors)
                    {
                        ModelState.AddModelError(error.Code, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmAccount(ConfirmAccount model)
        {
            return View(model);
        }

        [HttpPost]
        [ActionName("ConfirmAccount")]
        public async Task<IActionResult> Confirm(ConfirmAccount model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email).ConfigureAwait(false);
                if(user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with the given email does not found");
                    return View(model);
                }
                var result = await (_userManager as CognitoUserManager<CognitoUser>).ConfirmSignUpAsync(user, model.ConfirmationCode, true).ConfigureAwait(false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError(error.Code, error.Description);
                    }
                    return View(model);
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ForgotPassword()
        {
            var model = new ForgotPassword();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(ForgotPassword model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email).ConfigureAwait(false);
                if(user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    ModelState.AddModelError("NotFound", "A user with the given email does not found");
                    return View(model);
                }
                user.ForgotPasswordAsync().Wait();
                return RedirectToAction("ConfirmNewPassword");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmNewPassword()
        {
            var model = new ConfirmNewPassword();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmNewPassword(ConfirmNewPassword model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email).ConfigureAwait(false);
                if(user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with the given email does not found");
                    return View(model);
                }

                await user.ConfirmForgotPasswordAsync(model.ConfirmationCode, model.NewPassword);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        public async Task<IActionResult> SignIn()
        {
            var model = new SignIn();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(SignIn model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false).ConfigureAwait(false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("LoginError", "Email and password do not match");
            }
            return View(model);
        }
    }
}

WebAdvert.Web/Views/Accounts/SignIn.cshtml
@model WebAdvert.Web.Models.Accounts.SignIn

@{
    ViewData["Title"] = "SignIn";
}

<h4>SignIn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Accounts" asp-action="SignIn">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="RememberMe" /> @Html.DisplayNameFor(model => model.RememberMe)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="SignIn" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <a asp-controller="Accounts" asp-action="SignUp">
            Not a member? SignUp here
        </a>
    </div>
    <div class="col-md-2">
        <a asp-controller="Accounts" asp-action="ForgotPassword">
            Forgot password?
        </a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}